#
# Blog Settings
#
author: Mathieu Brun
description: One line after another...
url: https://mathieubrun.github.io
title: Mathieu Brun
subtitle: one line after another
subscribe_rss: http://feeds.feedburner.com/mathieubrun
encoding: UTF-8

# Github repositories
github_user: mathieubrun
github_repo_url: https://github.com/mathieubrun/mathieubrun.github.io/

# Disqus Comments
disqus_short_name: mathieubrungithubio
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-4184817-4
google_analytics_site_name: mathieubrun.github.io

# Quantcast
quantcast_tracking_id: p-CRnYZb4H0vFLg

#
# Jekyll Settings
#

# GitHub Defaults
lsi: false
markdown: kramdown
highlighter: rouge

# UTF-8 & parse errors fix
permalink: /archive/:year/:month/:day/:title
paginate: 5
paginate_path: "/page/:num"
category_dir: categories

twitter_handle: "mathieu_b"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll_github_sample