#
# Blog Settings
#
author: Mathieu
description: One line after another...
url: https://mathieubrun.github.io
title: Cogimator
subtitle: one line after another
subscribe_rss: http://feeds.feedburner.com/Cogimator
encoding: UTF-8

# Github repositories
github_user: mathieubrun
github_repo_url: https://github.com/mathieubrun/mathieubrun.github.io/

# Disqus Comments
disqus_short_name: mathieubrungithubio
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-4184817-4
google_analytics_site_name: mathieubrun.github.io

# Quantcast
quantcast_tracking_id: p-CRnYZb4H0vFLg

addthis_profile_id: ra-52e6c6e305561232

#
# Jekyll Settings
#

# GitHub Defaults
lsi: false
pygments: true
safe: true

# UTF-8 & parse errors fix
markdown: redcarpet
permalink: /archive/:year/:month/:day/:title/
paginate: 5
paginate_path: "page/:num"
category_dir: categories
