#
# Blog Settings
#
author: Mathieu
description: One line after another...
url: http://mathieubrun.github.io
title: Cogimator
subtitle: one line after another
subscribe_rss: http://feeds.feedburner.com/Cogimator

# Github repositories
github_user: mathieubrun
github_repo_url: https://github.com/mathieubrun/mathieubrun.github.io/

# Disqus Comments
disqus_short_name: cogimator
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-4184817-1

addthis_profile_id: ddsd
twitter_tweet_button: true
#
# Jekyll Settings
#

# GitHub Defaults
lsi: false
pygments: true
safe: true

# UTF-8 & parse errors fix
markdown: redcarpet
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories
